# Generated by Django 2.2.3 on 2020-01-30 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_code', models.TextField()),
                ('course_name', models.TextField()),
                ('course_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('req_1_id', models.IntegerField()),
                ('req_1_type', models.IntegerField()),
                ('logic_connector', models.IntegerField()),
                ('req_2_id', models.IntegerField()),
                ('req_2_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.IntegerField(primary_key=True, serialize=False)),
                ('program_name', models.TextField()),
                ('program_desc', models.TextField()),
                ('program_base_requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapBackend.Requirement')),
            ],
        ),
    ]
