# Generated by Django 2.2.3 on 2020-01-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='logic_connector',
            field=models.TextField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_1_type',
            field=models.TextField(choices=[('RequirementID', 'Nested Requirement'), ('CourseID', 'Required Course')], default='RequirementID'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='req_2_type',
            field=models.TextField(choices=[('RequirementID', 'Nested Requirement'), ('CourseID', 'Required Course')], default='RequirementID'),
        ),
    ]
