# Generated by Django 2.2.3 on 2020-01-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapBackend', '0002_auto_20200129_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_department',
            field=models.TextField(default='Mathematics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_faculty',
            field=models.TextField(default='Mathematics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_season',
            field=models.TextField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring')], default='Fall'),
        ),
    ]
