# Generated by Django 3.0.12 on 2023-04-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
