# Generated by Django 3.0.3 on 2021-01-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementgroup',
            name='courseRankingScheme',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='requirementgroup',
            name='shortDesc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
